---
- name: Make app directory
  file: >
    path={{ item }}
    state=directory
    mode=4644
    owner="{{ application_user }}"
    group="{{ application_group }}"
  with_items:
    - "{{ application_base }}"
    - "{{ application_base }}/logs"

- name: Get source
  git:
    repo: "{{ server_git_repository }}"
    dest: "{{ application_root }}"

- name: Change owner
  command: "chown -R {{ application_group }}:{{ application_user }} {{ application_base }}"

- name: Build source
  pip: >
    virtualenv={{ virtualenv_path }}
    requirements={{ application_root }}/requirements.txt
  notify: restart app
