---
- name: Make app directory
  file: >
    path={{ item }}
    state=directory
    mode=644
    owner="{{ application_user }}"
    group="{{ application_group }}"
  with_items:
    - /usr/local/webapp
    - /usr/local/webapp/logs

- name: Get server source
  git:
    repo: "{{ server_git_repository }}"
    dest: "{{ application_root }}"

- name: Change owner server source
  command: "chown -R {{ application_group }}:{{ application_user }} {{ application_root }}"

- name: Build server source
  pip: >
    virtualenv={{ virtualenv_path }}
    requirements={{ application_root }}/requirements.txt
  notify: restart app
