---
- name: Make app directory
  file: >
    path={{ item }}
    state=directory
    mode=4774
    owner="{{ application_user }}"
    group="{{ application_group }}"
  with_items:
    - "{{ application_base }}"
    - "{{ application_base }}/logs"
    - "{{ application_base }}/stat"

- name: Build source
  become: yes
  become_method: sudo
  become_user: apps_user
  shell: '/usr/local/bin/mybook-release.sh'

- name: Stop service
  become: yes
  become_method: sudo
  become_user: apps_user
  shell: '/usr/local/bin/mybook-stop.sh'

- name: Start service
  become: yes
  become_method: sudo
  become_user: apps_user
  shell: '/usr/local/bin/mybook-start.sh'
