- name: Install start/stop script
  template: >
    src="{{ item }}.j2"
    dest="/usr/local/bin/{{ item }}"
    owner={{ application_user }}
    group={{ application_group }}
    mode=0744
  with_items:
    - mybook-start.sh
    - mybook-stop.sh
