---
- name: Install nginx
  apt: >
    name=nginx
    state=present
  notify: restart nginx

- name: Remove the default site
  file: >
    path=/etc/nginx/conf.d/default.conf
    state=absent
  notify: restart nginx

- name: Create nginx configurations
  template: >
    src="{{ item }}.j2"
    dest="/etc/nginx/{{ item }}"
    owner=root
    group=root
    mode=0644
  with_items:
    - nginx.conf
  notify: restart nginx
